import './globals.css'
import { Inter } from 'next/font/google'
import { headers, cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, } : { children: React.ReactNode }) {
  
  const headersList = headers()
  const middlewareSet = headersList.get('middlewareSet')

  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <h1 className="text-4xl font-bold mb-4">Root Layout</h1>
          <p>login: {middlewareSet}</p>
        </div>
        {children}
      </body>
    </html>
  )
}
