import ClientLogout from '@/common/component/clientlogout'
import './globals.css'
import { Inter } from 'next/font/google'
import { headers, cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children, } : { children: React.ReactNode }) {
  
  const headersList = headers()
  const middlewareSet = headersList.get('middlewareSet')

  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="bg-gray-900 text-white py-4 px-8">
        <h1 className="text-4xl font-bold mb-4">Root Layout</h1>
        <p className="text-xl">Login: {middlewareSet}</p>
        <ClientLogout middlewareSet={middlewareSet} />
      </div>
        {children}
      </body>
    </html>
  )
}
